apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    service: redis
    apps: wordpress

spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379