apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
data:
  MYSQL_ROOT_PASSWORD: Y2hhbmdlbWU=  # Changeme
  MYSQL_DATABASE: ZGJfd29yZHByZXNz  # db_wordpress
  MYSQL_USER: dXNlcl93b3JkcHJlc3M=  # user_wordpress
  MYSQL_PASSWORD: cGFzc193b3JkcHJlc3M=  # pass_wordpress

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress
data:
  DB_Host: deploy-mariadb-0.mariadb.wordpress
  SESSION: ON
  PREFIX_SESSION: wpuser
  SESSION_HOST: redis.wordpress