apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    service: webserver-services
    apps: wordpress

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    service: webserver
    apps: wordpress