apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    type: webserver

spec:
  replicas: 3

  selector:
    matchLabels:
      service: webserver
      apps: wordpress

  template:
      metadata:
        name: wordpress
        labels:
          service: webserver
          apps: wordpress

      spec:
        containers:
          - name: webserver
            image: modinbah/wordpress_nginx
            ports:
              - containerPort: 80
            env:
              - name: DB_HOST
                value: "mariadb"
              - name: DB_NAME
                value: "db_wordpress"
              - name: DB_USER
                value: "user_wordpress"
              - name: DB_PASSWORD
                value: "pass_wordpress"
              - name: SESSION
                value: "ON"
              - name: PREFIX_SESSION
                value: "wpuser"
              - name: SESSION_HOST
                value: "redis"

